version: '3.5'

services:
  app:
    image: dockmelo/desafio-node-api
    container_name: nodejs-desafio
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh node index.js
    networks: 
      - desafio
    volumes:
      - ./nodejs:/usr/src/app
    tty: true
    ports:
      - 3000:3000
    depends_on: 
      - db
      - nginx

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: database
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - desafio
    depends_on: 
      - nginx

  nginx:
    image: dockmelo/desafio-nginx-proxy
    container_name: nginx-desafio
    restart: always
    ports:
      - 8080:80
    networks:
      - desafio


networks: 
  desafio:
    driver: bridge