version: '3'

services:
  app:
    build:
      context: ./nodejs
    container_name: nodejs
    networks: 
      - desafio
    volumes:
      - ./nodejs:/usr/src/app
    tty: true
    ports:
      - 3000:3000
    depends_on: 
      - db
      - nginx

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: database
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - desafio
    depends_on: 
      - nginx

  nginx:
    build:
        context: ./nginx
    container_name: nginx
    restart: always
    ports:
      - 8080:80
    networks:
      - desafio


networks: 
  desafio:
    driver: bridge